modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/dragon-forge/OnlineDisplays/issues"
license = "All rights reserved"

[[mods]]
modId = "onlinedisplays"
version = "${file.jarVersion}"
displayName = "Online Displays"
updateJSONURL = "https://api.modrinth.com/updates/bhEwCNbH/forge_updates.json"
displayURL = "http://dccg.herokuapp.com/api/fmlhp/785509"
authors = "Zeitheron"
logoFile = "display_logo.png"

description = '''
This mod is intended for Creative Mode use, but can be also used in Survival Mode, if chosen to.
Online Displays allows putting up an image, positioning, rotating and scaling it to your exact need.
Additionally, the lighting of it may be disabled, essentially rendering it as "emissive*"
'''

[[dependencies.onlinedisplays]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"

[[dependencies.onlinedisplays]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.onlinedisplays]]
modId = "hammerlib"
mandatory = true
versionRange = "[19.5.57,)"
ordering = "NONE"
side = "BOTH"
